bcgov/cas-ggircs

- Jenkinsfile
Since we've discovered that pushing built images from Circle to OpenShift is going to be a pain, let's start this repo off with a passing build pipeline. The pipeline should be adjusted to test any and all code added to the repo.
> Add a no-op configuration for Jenkins

- Makefile
- test/fixture/csv_import_fixture.csv
- test/variable_test.sql
this is an example of how to get a relative path to a fixture file passed into the test suite as an absolute path that the database can read
> use a fixture to populate a table

- deploy/materialized_view_final_report.sql
- revert/materialized_view_final_report.sql
- sqitch.plan
- test/unit/materialized_view_final_report_test.sql
- verify/materialized_view_final_report.sql
continuation of #30 with prior commits squashed
This view identifies the final `ghgr_import_id` for every `swrs_report_id` so queries can be constructed that use only the latest version of an xml report from the Single Window Reporting System.
> final report view

- Makefile
- Readme.md
In Makefile:
- `make verify` only checks dependencies that are not installed by `make install`
- `make verify` checks that the database server contains the appropriate role
- `make install` uses `cpanm` to install the CPAN dependencies listed in `cpanfile`
- if `cpanm` isn't installed, `make install will install it using `cpan`
- before installing `pgTAP` checks whether elevated privileges (or a different user) are needed. If so, warn the user that they have to run the `pgTAP` `make install` manually
In README:
- updated the order of base steps (`verify` before `install`)
- added `createdb` steps
- do not list dependencies  that are installed by Makefile
- added info regarding the role that must exist in postgres
> Makefile uses cpanfile + extra checks

- deploy/function_export_mv_to_table.sql
- deploy/materialized_view_parent_organisation.sql
- test/unit/function_export_mv_to_table_test.sql
- test/unit/materialized_view_activity_test.sql
- test/unit/materialized_view_address_test.sql
- test/unit/materialized_view_contact_test.sql
- test/unit/materialized_view_descriptor_test.sql
- test/unit/materialized_view_emission_test.sql
- test/unit/materialized_view_facility_test.sql
- test/unit/materialized_view_final_report_test.sql
- test/unit/materialized_view_flat_test.sql
- test/unit/materialized_view_fuel_test.sql
- test/unit/materialized_view_measured_emission_factor_test.sql
- test/unit/materialized_view_naics_test.sql
- test/unit/materialized_view_organisation_test.sql
- test/unit/materialized_view_parent_organisation_test.sql
- test/unit/materialized_view_permit_test.sql
- test/unit/materialized_view_unit_test.sql
@wenzowski @hamzajaved 
I've cleaned up the linebreaks in all the files that were broken up with || and blocked them together with $$. If either of you have more sweeping formatting changes that you'd like to see done before this sprint pop em in a comment.
> Clean-up linebreaks (use $$ instead of ||)

- deploy/materialized_view_report.sql
- test/unit/materialized_view_report_test.sql
metabase was crashing  on refresh. We found it was because it was hung up on the integer type of reporting year.
> reporting year datatype change

- Makefile
- openshift/deploymentconfig/cas-ggircs.yml
will be more efficient when sqitchers/sqitch#477 lands, and will result in less downtime during redeploys
Probably also want to run the exporter function via psql on each deploy, in addition to via cron
> automatically revert/deploy via sqitch

- .s2i/bin/assemble
- Makefile
- cpanfile
Devs can run `make install_cpandeps` to install the latest version of sqitch. The `rebase --revised` feature is not in use in the deployment config as it requires the export function to be able to do a partial export
> Use sqitch version with --revised feature

- deploy/swrs/transform/function/clone_schema.sql
There were still some dependencies left between the views in swrs, leading to errors when loading the data
> clone_schema now recreates views in the correct order

- .circleci/config.yml
- shipit.yml
When running non-interactively, git submodules should always be checked
out exactly as committed. The `git submodule update --remote` command
should be use interactively to fetch the latest head of all submodules
per the gitmodules config and if any referenceds have changed they
should be committed manually.
> pinned git references should be respected

- .tool-versions
- deploy/swrs/public/table/report.sql
- deploy/swrs/public/view/carbon_tax_calculation.sql
- deploy/swrs/public/view/pro_rated_carbon_tax_rate.sql
- deploy/swrs/public/view/pro_rated_fuel_charge.sql
- deploy/swrs/public/view/pro_rated_implied_emission_factor.sql
- deploy/swrs/transform/materialized_view/report.sql
- test/unit/materialized_view_report_test.sql
- test/unit/view_attributable_emission_with_details_test.sql
- test/unit/view_pro_rated_carbon_tax_rate_DEPRECATED.sql
- test/unit/view_pro_rated_implied_emission_factor_DEPRECATED.sql
- test/unit/view_report_with_org_test.sql
- set reporting_period_duration to integer in report
- remove unnecessary casting to int in other files
> Properly type reporting_period_duration as integer

- Makefile
This fixes the failing `test-local-cluster` CI job on `develop`
> test: update the mocked storageclass to match cas-postgres

- Makefile
Looks like I deleted too many things in #144
> test: ggircs needs the gluster-file storage type for its "data" PVC

- openshift/deploy/job/etl-revert.yml
This behavior will be updated soon
> ci: don't drop eccc_xml_file table when deploying

- helm/cas-ggircs/Chart.lock
- helm/cas-ggircs/Chart.yaml
This enables db health checks and graceful termination
> chore: update cas-postgres chart dependency to 0.5.0

- deploy/private/prune_test_organisations_and_facilities.sql
- deploy/private/schema.sql
- eccc/extract/app/extract_zips.py
- helm/cas-ggircs/templates/etl/eccc-upload-cron.yaml
- revert/private/prune_test_organisations_and_facilities.sql
- revert/private/schema.sql
- sqitch.plan
- test/style/schema_test.sql
- test/unit/prune_test_organisations_and_facilities_test.sql
- verify/private/prune_test_organisations_and_facilities.sql
- verify/private/schema.sql
Preventing Test / Quality Control reports from being downloaded from ECCC, and uploaded to GCP
> Fix: ignore test reports on eccc load

- ggircs-app/app/package.json
- ggircs-app/app/yarn.lock
> chore: update next to 10.2.0

- deploy/swrs/public/table/report_001.sql
- deploy/swrs/transform/materialized_view/report_001.sql
- ggircs-app/app/package.json
- ggircs-app/app/yarn.lock
- revert/swrs/public/table/report_001.sql
- revert/swrs/transform/materialized_view/report_001.sql
- sqitch.plan
- test/unit/materialized_view_report_test.sql
- verify/swrs/public/table/report_001.sql
- verify/swrs/transform/materialized_view/report_001.sql
ETL failed due to an `update_comment` larger than the allotted varchar size for swrs.report / swrs_transform.report.
This PR increases the size limit for update_comment in both the table and materialized view.
> Fix: increase varchar limit for update_comment

- deploy/swrs/transform/materialized_view/report_001.sql
- deploy/swrs/transform/materialized_view/report_001@v1.3.0.sql
- revert/swrs/transform/materialized_view/report_001.sql
- revert/swrs/transform/materialized_view/report_001@v1.3.0.sql
- sqitch.plan
- verify/swrs/transform/materialized_view/report_001@v1.3.0.sql
- The migration in https://github.com/bcgov/cas-ggircs/pull/252 cannot be done by our deploy user (and is probably bad practice to edit this table anyway)
- This PR reverts that migration & fixes the update_comment datatype issue with a drop cascade & recreates the dropped items.
> fix: revert bad migration & fix update_comment datatype

- .tool-versions
Deploying this will should pull the latest `debian:10` image, which has additional security fixes
> chore: CVEs

- ggircs-app/app/package.json
- ggircs-app/app/yarn.lock
updating postgraphile and one of its dependencies to solve CVE-2021-32640
> chore: fixing CVE-2021-32640

- .secrets.baseline
- helm/cas-ggircs/templates/app/cronJobs/cron-app-user.yaml
- helm/cas-ggircs/templates/app/secret.yaml
- helm/cas-ggircs/values.yaml
the user that runs the relay queries needed to be defined in order to be used in our templates.
> chore: define relay user for templates

- ggircs-app/app/.eslintrc.js
- ggircs-app/app/components/XmlDiff/RenderDiff.tsx
- ggircs-app/app/components/XmlDiff/ReportSelector.tsx
- ggircs-app/app/package.json
- ggircs-app/app/pages/ggircs/xml-diff.tsx
- ggircs-app/app/tests/unit/pages/ggircs/xml-diff.test.tsx
- ggircs-app/app/yarn.lock
- test/data/dev/deploy_data.sh
- test/data/dev/dev_history_data.sql
Fixing the diffing. The issue was that `useRouter` was being used in 2 components on different branches of the rendering tree, and ordering of some react hooks.
This is because `useRouter` uses React's Context API, which is only unique per branch of the render tree
> Fix: diff broken after relay 13 upgrade

- shipit.yml
Shipit introspects your repo and tries to install your dependencies. We don't want to do this when we deploy, everything is handled by `make install`. Overriding the dependencies in shipit.yml should make shipit skip the install dependencies step.
> chore: override dependencies in shipit.yaml
