.circleci/config.yml
Makefile
deploy/schema_ggircs.sql
revert/schema_ggircs.sql
sqitch.conf
sqitch.plan
verify/schema_ggircs.sql

tested on circle (not Jenkins)

use sqitch to deploy schema

---

Readme.md

I copy pasted the link including the backticks so the whole things shows as text on the readme

removed backticks around circleCI badge so it will render properly

---

doc/Architecture.md

begin to record established conventions

document architecture

---

deploy/materialized_view_organisation.sql
test/unit/materialized_view_organisation_test.sql

rebased: add xml import test fixture to matview organisation

---

deploy/materialized_view_flat.sql
sqitch.plan
test/unit/materialized_view_flat_test.sql

hey @hamzajaved this isn't quite as robust as what we were discussing, but I think it provides the relevant context to an analyst in a more concise manner

add a context column to the flat view

---

deploy/materialized_view_flat.sql
deploy/materialized_view_organisation.sql

this is holding back manual integration testing

both flat and organisation mviews should be created with no data

---

Readme.md

we have some folks coming to check this code out, so we should make it easy for them to get started

Improve installation instructions

---

deploy/materialized_view_emission.sql
revert/materialized_view_emission.sql
sqitch.plan
test/unit/materialized_view_emission_test.sql
verify/materialized_view_emission.sql

added matview fuel to schema ggircs_swrs

---

deploy/materialized_view_contact.sql
revert/materialized_view_contact.sql
sqitch.plan
test/unit/materialized_view_contact_test.sql
verify/materialized_view_contact.sql

All parents of Contact are:
ConfidentialityRequest
RegistrationData
Contacts
All parents of Contacts are:
RegistrationData
VerifyTombstone

create contact matview

---

deploy/materialized_view_parent_organisation.sql
revert/materialized_view_parent_organisation.sql
sqitch.plan
test/style/column_test.sql
test/unit/materialized_view_parent_organisation_test.sql
verify/materialized_view_parent_organisation.sql

All children of ParentOrganisation:
PercentageOwned
Details
Address
MailingAddress
LegalName
All parents of ParentOrganisation:
ParentOrganisations
RegistrationData

create parent organisation matview

---

deploy/materialized_view_facility.sql
test/unit/materialized_view_facility_test.sql
test/unit/materialized_view_identifier_test.sql

test verify tombstone and use compound primary key

adjust facility view to be consistent with conventions

---

deploy/materialized_view_fuel.sql
test/style/column_test.sql
test/unit/materialized_view_fuel_test.sql

AlternativeMethodologyDescription
AnnualFuelAmount
AnnualSteamGeneration
AnnualWeightedAverageCarbonContent
AnnualWeightedAverageHighHeatingValue
Emissions
FuelClassification
FuelDescription
FuelType
FuelUnits (Units union-ed into FuelUnits)
MeasuredConversionFactors
MeasuredEmissionFactor
MeasuredEmissionFactors
MeasuredEmissionFactorUnitType
OtherFlareDetails
WastewaterProcessingFactors
Q1
Q2
Q3
Q4

update fuel columns - get all descriptors

---

deploy/materialized_view_flat.sql
revert/materialized_view_flat.sql
test/unit/materialized_view_flat_test.sql

adds parent and grandparent context

improve flat view to work on all data

---

deploy/table_ignore_organisation.sql
revert/table_ghgr_import.sql
revert/table_ignore_organisation.sql
sqitch.plan
test/style/table_test.sql
test/unit/table_ignore_organisation_test.sql
verify/table_ghgr_import.sql
verify/table_ignore_organisation.sql

These should probably be excluded from the `ggircs_swrs.final_report` list as well

Add a list of SWRS test orgs to ignore

---

deploy/materialized_view_permit.sql
revert/materialized_view_permit.sql
sqitch.plan
test/style/column_test.sql
test/unit/materialized_view_permit_test.sql
verify/materialized_view_permit.sql

All parents of Permit:
Permits
PermitList
All children of Permit:
IssuingAgency
IssuingDeptAgencyProgram
PermitNumber

create permit matview

---

deploy/materialized_view_identifier.sql
test/style/column_test.sql
test/unit/materialized_view_identifier_test.sql

I don't understand the problem (not getting values from the path: RegistrationData/Facility/Identifiers/IdentifierList/Identifier)?
It looks to me like the values are being extracted fine.
I did go through and update Identifier to use our new pkey convention (removed id and history id, created unique index on columns)

update identifier xpaths

---

deploy/materialized_view_naics.sql
test/style/column_test.sql
test/unit/materialized_view_naics_test.sql

Updated to the new pkey convention and wrote a fixture test that it naics joins facility successfully.

update naics pkey to new pkey convention

---

deploy/materialized_view_report.sql

implement recommendations made by Konstantin

---

deploy/materialized_view_final_report.sql
sqitch.plan
test/unit/materialized_view_final_report_test.sql

I added to the fixtiure and wrote a test in materialized_view_final_report_test to check that the ignored value is actually being ignored.

joined ignore_organisation on final_report

---

deploy/materialized_view_fuel.sql
deploy/materialized_view_measured_emission_factor.sql
revert/materialized_view_measured_emission_factor.sql
sqitch.plan
test/unit/materialized_view_fuel_test.sql
test/unit/materialized_view_measured_emission_factor_test.sql
verify/materialized_view_measured_emission_factor.sql

measured_emission_factor(s) in any context is a fairly new descriptor.
The first instance where Fuel/MeasauredEmissionFactor is not null is ghgr_import_id 31813
The first instance where Fuel/MeasuredEmissionFactors/MeasuredEmissionFactor is not null is ghgr_import_id 41048

Create emission factors matview

---

deploy/materialized_view_organisation.sql
deploy/materialized_view_report.sql
test/unit/materialized_view_activity_test.sql
test/unit/materialized_view_address_test.sql
test/unit/materialized_view_contact_test.sql
test/unit/materialized_view_descriptor_test.sql
test/unit/materialized_view_emission_test.sql
test/unit/materialized_view_facility_test.sql
test/unit/materialized_view_final_report_test.sql
test/unit/materialized_view_flat_test.sql
test/unit/materialized_view_fuel_test.sql
test/unit/materialized_view_organisation_test.sql
test/unit/materialized_view_parent_organisation_test.sql
test/unit/materialized_view_permit_test.sql
test/unit/materialized_view_unit_test.sql

depends on #32.
There is some work being done on report in #32 that may affect the fk join from final_report to report so I have left it until #32 is merged.

update all pkeys, add tests on fkey joins & add xml import tests

---

Makefile
Readme.md
cpanfile

replaces #61 due to Circle CI failure

Make makefile more robust and helpful

---

openshift/cas-ggircs-deploy-config-template.yml

without this, postgres is ephemeral

correct mount path to add persistence to postgres

---

deploy/materialized_view_activity.sql
deploy/materialized_view_address.sql
deploy/materialized_view_contact.sql
deploy/materialized_view_descriptor.sql
deploy/materialized_view_emission.sql
deploy/materialized_view_facility.sql
deploy/materialized_view_flat.sql
deploy/materialized_view_fuel.sql
deploy/materialized_view_identifier.sql
deploy/materialized_view_measured_emission_factor.sql
deploy/materialized_view_naics.sql
deploy/materialized_view_organisation.sql
deploy/materialized_view_parent_organisation.sql
deploy/materialized_view_permit.sql
deploy/materialized_view_report.sql
deploy/materialized_view_unit.sql

it's a pain to `explain`
https://thoughtbot.com/blog/advanced-postgres-performance-tips

remove all the unnecessary cte business

---

deploy/function_export_mv_to_table.sql
test/unit/function_export_mv_to_table_test.sql

Add Identifier / Naics foreign keys to Facility

---

deploy/function_export_mv_to_table.sql
test/unit/function_export_mv_to_table_test.sql

Created fk relations:
Address,
Contact,
Parent Org,
Descriptor,
Fuel,
Naics,
Identifier
--> Report
https://youtrack.button.is/agiles/101-1/102-13?issue=GGIRCS-434
Facility & Activity already had fk relations defined on Report

Add fk relations on report

---

.circleci/config.yml

should send notifications to the [Continuous Integration](https://teams.microsoft.com/l/channel/19%3a46b058d538184f5195f872058007872a%40thread.skype/Continuous%2520Integration?groupId=a00d3135-7e96-47a0-817e-0086ec993205&tenantId=55bc71c2-5150-4ff8-bbcd-d94bc32bf20c) channel

notify ms teams on test run

---

deploy/function_export_mv_to_table.sql
deploy/table_contact.sql
deploy/view_attributable_emission.sql
deploy/view_attributable_emissions_with_details.sql
deploy/view_carbon_tax_calculation.sql
deploy/view_report_with_org.sql
revert/table_fuel.sql
revert/view_attributable_emission.sql
revert/view_attributable_emissions_with_details.sql
revert/view_report_with_org.sql
sqitch.plan
test/unit/function_export_mv_to_table_test.sql
test/unit/view_carbon_tax_calculation_test.sql
verify/view_attributable_emission.sql
verify/view_attributable_emissions_with_details.sql
verify/view_report_with_org.sql

Added id's to carbon_tax_calculation:
organisation
single facility
lfo facility
naics
naics mapping
Added id's to contact:
organisation

Add FK's to carbon tax calculator

---

ciip/extract/extract.py
ciip/extract/extract_emission.py
ciip/extract/extract_facility.py
deploy/ciip/view_compare_ciip_swrs_emission.sql
openshift/imagestream/cas-ggircs-postgres-mirror.yml
revert/ciip/view_compare_ciip_swrs_emission.sql
sqitch.plan
verify/ciip/view_compare_ciip_swrs_emission.sql

Also 
- attempt to link facilities using the name if GHG id fails
- fix postgres mirror image tagging

Extract ciip emissions and create view to compare to swrs emissions

---

Makefile
openshift/buildconfig/cas-ggircs-metabase-preview-build.yml
openshift/buildconfig/cas-ggircs-metabase-preview.yml
openshift/deploymentconfig/cas-ggircs-metabase-preview.yml
openshift/route/cas-ggircs-metabase-preview.yml
openshift/service/cas-ggircs-metabase-preview.yml

The preview version is available at https://metabase-preview-wksv3k-test.pathfinder.gov.bc.ca/

Deploy the latest version of metabase (0.33.0-RC1)

---

Makefile
openshift/deploy/secret/ggircs-postgres.yml

depends on https://github.com/bcgov/cas-postgres/pull/29

feature: edit secrets and makefile to create read-only postgres user

---

test/data/Report_10692X.xml
test/data/Report_10759X.xml
test/data/Report_11033X.xml
test/data/Report_11233X.xml
test/data/Report_11266X.xml
test/data/Report_11324X.xml

This allows importing the data in the CIIP portal project

test: some test reports should have the 2018 reporting year

---

Readme.md
deploy/swrs/transform/table/ignore_organisation_001.sql
revert/swrs/transform/table/ignore_organisation_001.sql
sqitch.plan
verify/swrs/transform/table/ignore_organisation_001.sql

- adds swrs_organisation_id 113130 and 112552 to the swrs exclusion list
- adds documentation on ignoring organisations

Feat: update ignore_organisation table

---

.circleci/config.yml
helm/cas-ggircs/Chart.yaml

NSP -> KNP release
chart v0.2.1
app v1.1.0

chore: release v1.1.0

---

deploy/swrs/add_missing_indices.sql
revert/swrs/add_missing_indices.sql
sqitch.plan
test/unit/all_foreign_keys_are_indexed_test.sql
verify/swrs/add_missing_indices.sql

- pgTap test to ensure all fkeys are indexed
- migration to add an index to each foreign key if it does not exist

Feat: add missing indices

---

helm/cas-ggircs/templates/etl/deploy-load-testing-data.yaml
helm/cas-ggircs/templates/etl/etl-deploy-cron.yaml

I think the parenthesis around NAMESPACE is a problem?
"$(NAMESPACE)" ---> "$NAMESPACE"

chore: remove bad parenthesis

---

helm/cas-ggircs/templates/etl/deploy-load-testing-data.yaml
helm/cas-ggircs/templates/etl/etl-deploy-cron.yaml

chore: fix path to deploy dev data script

---

ggircs-app/app/components/Dashboard/SwrsDataAccessCard.tsx
ggircs-app/app/components/Layout/DefaultLayout.tsx
ggircs-app/app/components/Layout/Header.tsx
ggircs-app/app/components/LoadingSpinner.tsx
ggircs-app/app/components/LoginButton.tsx
ggircs-app/app/package.json
ggircs-app/app/yarn.lock

integrating the bc-gov theme of https://github.com/button-inc/service-development-toolkit into the app
#265 
2 elements are currently blocking us from removing bootstrap:
- `Popover` 
- `ListGroup`

Feat: service development toolkit

---

Makefile

- define namespace of route check

fix: multi giircs deploy depending on namespace

---

Makefile
helm/cas-ggircs/Chart.yaml
sqitch.plan

fix: update swrs dags location + release v1.4.1

---

helm/cas-ggircs/templates/app/deploy.yaml
helm/cas-ggircs/values.yaml

readiness probe should use http

fix: update readiness probe / add liveness probe

---

helm/cas-ggircs/Chart.yaml
sqitch.plan

chore(release): v1.10.0

---

ggircs-app/app/package.json
ggircs-app/app/pages/request-access-notice.tsx
ggircs-app/app/server/helpers/userGroupAuthentication.js
ggircs-app/app/yarn.lock

fix: unauthorized idir users are redirected to /request-access-notice

---

ggircs-app/app/lib/relay/client.ts
ggircs-app/app/yarn.lock

Fix: disable mutation batching

---

.circleci/config.yml
Readme.md
eccc/file_server/requirements.txt
ggircs-app/app/package.json
ggircs-app/app/yarn.lock
helm/cas-ggircs/Chart.yaml
sqitch.plan

Chore: release v1.13.2

---

.pre-commit-config.yaml
CHANGELOG.md
ggircs-app/app/package.json
ggircs-app/schema/sqitch.plan
package.json
sqitch.plan

Chore: release 1.14.0

---

CHANGELOG.md
ggircs-app/app/package.json
ggircs-app/schema/sqitch.plan
helm/cas-ggircs/Chart.yaml
package.json
sqitch.plan

Chore: release 1.14.1

---

helm/cas-ggircs/templates/app/cronJobs/cron-app-user.yaml
helm/cas-ggircs/templates/app/cronJobs/cron-deploy-data.yaml
helm/cas-ggircs/templates/etl/db-create-readonly-user-cron.yaml
helm/cas-ggircs/templates/etl/db-init-cron.yaml
helm/cas-ggircs/templates/etl/deploy-load-testing-data.yaml
helm/cas-ggircs/templates/etl/eccc-extract-attachments.yaml
helm/cas-ggircs/templates/etl/eccc-extract-xml-files.yaml
helm/cas-ggircs/templates/etl/eccc-extract-zips-cron.yaml
helm/cas-ggircs/templates/etl/eccc-upload-cron.yaml
helm/cas-ggircs/templates/etl/etl-deploy-cron.yaml
helm/cas-ggircs/templates/etl/etl-revert-cron.yaml
helm/cas-ggircs/templates/etl/ghg-credentials-issuer-cron.yaml

[ZH CARD](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-ggircs/499)

chore: 499 update cronjobs schedule

---

CHANGELOG.md
eccc/extract/app/zip_file_processor.py
ggircs-app/app/package.json
ggircs-app/schema/sqitch.plan
package.json
sqitch.plan

includes quarantining a bad swrs report

chore: release

---

ggircs-app/schema/deploy/types/jwt_token.sql
ggircs-app/schema/revert/types/jwt_token.sql
ggircs-app/schema/sqitch.plan

This is a fix the rewriting of history. It addresses the CI failures seen in CircleCI _without_ doing the history rewrite.

fix: revert sqitch plan history rewrite

---

helm/cas-ggircs/templates/app/route.yaml

Added IP whitelist to route.yaml per SO answer https://stackoverflow.developer.gov.bc.ca/questions/899?newreg=6df22d772f974f07895456f007ce0acc

Restrict app traffic to Zone B only
